#!/usr/bin/python3
import argparse
import os

import matplotlib.pyplot as plt
import numpy as np
import scipy.signal

import lib.tekdecode

parser = argparse.ArgumentParser(
    description='generates time-domain plots from oscilloscope data')
parser.add_argument('file',
                    help='csv/isf files from Tektronix scope', nargs='+')

args = parser.parse_args()

for file in args.file:

	voltage, sample_rate, length = lib.tekdecode.loadFile(file)

	voltage = voltage[int(len(voltage) - len(voltage) / 20):]

	time = np.arange(0, len(voltage)) * (1e6 / sample_rate)

	voltage *= 1e3

	plt.plot(time, voltage, label=file)
plt.ylabel('stage 2 output (mV)')
plt.xlabel('time (µs)')
plt.legend()
plt.grid(which='both')
plt.show()
