#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
import argparse

import argcomplete

parser = argparse.ArgumentParser(
	description='generates bode plots from time-domain oscilloscope data')

parser.add_argument('output',
                    help='output file, tab separated')
parser.add_argument('scope_data_input', metavar='scope-data-input',
                    help='file that contains the amplifier input')
parser.add_argument('scope_data_output', metavar='scope-data-output',
                    help='file that contains the amplifier output')
parser.add_argument('freq_start', metavar='freq-start', type=float,
                    help='sweep start frequency')
parser.add_argument('freq_stop', metavar='freq-stop', type=float,
                    help='sweep stop frequency')

parser.add_argument('--sweep-type', choices=['rigol-log', 'linear'],
                    default='rigol-log',
                    help='sweep type to estimate frequency')
parser.add_argument('--points', type=int, default=100,
                    help='number of points')
parser.add_argument('--periods', type=float, default=3,
                    help='number of sine periods to use for each frequency')
parser.add_argument('--show-fits', action='store_true',
                    help='show fit for every point')
parser.add_argument('--invert', action='store_true',
                    help='invert output signal')

parser.add_argument('--plot', action='store_true',
                    help='show final plot by calling plot-bode')
parser.add_argument('-y', '--yes', action='store_true',
                    help='overwrite output file')

parser.add_argument('--stopwatch', action='store_true',
                    help='show time required for different operations')

################################################################################

argcomplete.autocomplete(parser)
args = parser.parse_args()

# prevent autopep8 from moving these imports to the front
if True:
	import time
	import os
	from dataclasses import dataclass
	from multiprocessing import Pool

	import numpy as np
	import scipy.optimize
	import scipy.signal

	import lib.tekdecode

################################################################################

if not args.yes and os.path.exists(args.output):
	response = input('output file exists, overwrite? (y/N)')
	if response != 'y':
		exit(0)

################################################################################

time_start = time.time()


def report_duration(event):
	global time_start
	if args.stopwatch:
		print(f'time spent {event}: {time.time() - time_start:0.1f}s')
	time_start = time.time()

################################################################################


voltage_in, sample_rate, length = lib.tekdecode.loadFile(
	args.scope_data_input)
voltage_out, sample_rate_out, length_out = lib.tekdecode.loadFile(
	args.scope_data_output)

report_duration('loading files')

############################################################################

if sample_rate != sample_rate_out:
	print('files have different sample rates')
	exit(1)

if length != length_out:
	print('files have different lengths')
	exit(1)

if args.invert:
	voltage_out = -voltage_out
	report_duration('inverting output channel')

############################################################################


@dataclass
class FitResult:
	frequency: float
	amplitude: float
	phase: float
	offset: float
	time: np.array
	voltage: np.array


def sine(t, amplitude, angular_frequency, phase, offset):
	return amplitude * np.sin(angular_frequency * t - phase) + offset


def fitsine(T, U, freq_approx):
	try:
		downsample_factor = 1  # int(len(T) / 2000)

		if downsample_factor > 1:
			T = scipy.signal.decimate(T, downsample_factor, zero_phase=True)
			U = scipy.signal.decimate(U, downsample_factor, zero_phase=True)

		amplitude_max = np.max(np.abs(U)) or 0.01
		angular_frequency_approx = 2 * np.pi * freq_approx
		offset_mean = np.mean(U)

		def sine_phase(t, phase):
			return amplitude_max * np.sin(angular_frequency_approx * t - phase) + offset_mean

		(phase_approx), _ = scipy.optimize.curve_fit(
			sine_phase, T, U, [0], bounds=([- np.pi], [np.pi]))

		# do proper fit
		guess = [amplitude_max, angular_frequency_approx, phase_approx, offset_mean]
		bounds = (
			[amplitude_max * 0.7, angular_frequency_approx * 0.5, -np.pi, -amplitude_max],
			[amplitude_max, angular_frequency_approx / 0.5, np.pi, amplitude_max])
		result, _ = scipy.optimize.curve_fit(sine, T, U, guess, bounds=bounds)

		amplitude, angular_frequency, phase, offset = result

		return FitResult(amplitude=amplitude, frequency=angular_frequency / (2 * np.pi), phase=phase, offset=offset, time=T, voltage=U)
	except Exception as e:
		return None

############################################################################


def approx_freq_rigol_log(sample_index):
	# see https://www.batronix.com/pdf/Rigol/UserGuide/DG1000Z_UserGuide_EN.pdf page 109
	P = 10**(np.log10(args.freq_stop / args.freq_start) / (length / sample_rate))
	T = (sample_index / sample_rate) + np.log10(args.freq_start) / np.log10(P)
	return P**T


def approx_freq_linear(sample_index):
	return args.freq_start + (args.freq_stop - args.freq_start) * (sample_index / length)


approx_freq = {'rigol-log': approx_freq_rigol_log,
               'linear': approx_freq_linear}[args.sweep_type]

############################################################################


def get_slice_length(frequency):
	return int(args.periods * sample_rate / frequency)

############################################################################


def center_index_to_results(index_center):
	freq_approx = approx_freq(index_center)
	slice_length = get_slice_length(freq_approx)

	index_start = index_center - int(slice_length / 2)
	index_end = index_start + slice_length

	T = np.arange(0, slice_length) / sample_rate
	U_in = voltage_in[index_start: index_end]
	U_out = voltage_out[index_start: index_end]

	result_in = fitsine(
		T, U_in, freq_approx)
	result_out = fitsine(
		T, U_out, freq_approx)

	return result_in, result_out

############################################################################


center_indexes = np.linspace(get_slice_length(
        args.freq_start), length - get_slice_length(args.freq_stop), args.points).astype(int)

pool = Pool()
results = pool.map(center_index_to_results, list(center_indexes))
pool.close()
pool.join()

report_duration('fitting sine to data')

################################################################################

if args.show_fits:
	import matplotlib.pyplot as plt

############################################################################

# output arrays
Frequency = []
Gain = []
Phase = []

for (result_in, result_out) in results:
	if result_in is None or result_out is None:
		continue

	phi = result_in.phase - result_out.phase
	if phi < -np.pi:
		phi += 2 * np.pi
	if phi > np.pi:
		phi -= 2 * np.pi

	Frequency.append(result_in.frequency)
	Gain.append(result_out.amplitude / result_in.amplitude)
	Phase.append(phi)

	if args.show_fits:
		def plot_curve(result, color, label):
			plt.plot(result.time, result.voltage, '+', color=color,
                            label=f'{label}, fit:\nf: {result.frequency:0.1f} Hz\nA: {result.amplitude:0.3f} Vpp')
			plt.plot(result.time, sine(result.time, result.amplitude, result.frequency *
                                2 * np.pi, result.phase, result.offset), color= 'black')

		plot_curve(result_in, 'C0', 'input')
		plot_curve(result_out, 'C1', 'output')

		plt.legend(loc=1)
		plt.show()

Frequency = np.array(Frequency)
Gain = np.array(Gain)
Phase = np.array(Phase)

report_duration('creating final output values')

################################################################################

print(f'final data points: {len(Frequency)}')

################################################################################

with open(args.output, 'w') as file:
	file.write('# frequency (Hz), gain (V/V), phase (rad)')
	for (f, g, phi) in zip(Frequency, Gain, Phase):
		file.write(f'{f:0.1f}\t{g:0.3e}\t{phi:0.2f}\n')

	report_duration('writing values to table')

if args.plot:
	import subprocess
	subprocess.Popen(['plot-bode', args.output], close_fds=True,
	                 stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
