#!/usr/bin/python3
import argparse
import os

import matplotlib.pyplot as plt
import numpy as np
import scipy.signal

import lib.tekdecode

parser = argparse.ArgumentParser(
    description='generates time-domain plots from oscilloscope data')
parser.add_argument('file',
                    help='csv/isf files from Tektronix scope')

args = parser.parse_args()

voltage, sample_rate, length = lib.tekdecode.loadFile(args.file)

voltage = voltage[:100000]

time = np.arange(0, len(voltage)) * (1e6 / sample_rate)
voltage *= 1e-3

plt.plot(time, voltage, label=args.file)
plt.ylabel('stage 2 output (mV)')
plt.xlabel('time (µs)')
plt.legend()
plt.grid(which='both')
plt.show()
